name: Check for new bcrypt release

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  check-release:
    runs-on: ubuntu-latest

    outputs:
      latest-release: ${{ steps.latest.outputs.LATEST_RELEASE }}
      current-release: ${{ steps.current.outputs.CURRENT_RELEASE }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl jq

      - name: Get latest bcrypt release
        id: latest
        run: |
          BCRYPT_LATEST=$(curl -s https://pypi.org/pypi/bcrypt/json | jq -r '.info.version')
          echo "LATEST_RELEASE=$BCRYPT_LATEST" >> $GITHUB_OUTPUT
          echo "Latest bcrypt version: "$BCRYPT_LATEST

      - name: Get current bcrypt release for Power
        id: current
        run: |
          BCRYPT_CURRENT=$(curl -s https://api.github.com/repos/DahlitzFlorian/bcrypt-ppc64le/releases/latest | grep tag_name | cut -d '"' -f4)
          echo "CURRENT_RELEASE=$BCRYPT_CURRENT" >> $GITHUB_OUTPUT
          echo "Current bcrypt version on Power: "$BCRYPT_CURRENT

  build-new-release:
    needs: [check-release]
    if: needs.check-release.outputs.latest-release != needs.check-release.outputs.current-release
    uses: ./.github/workflows/build_bcrypt.yaml
    with:
      release: ${{ needs.check-release.outputs.latest-release }}
